baseURL = 'https://ulimativo.github.io/'
languageCode = 'en-us'
title = 'Ulimativo@Gihub.io'
theme= 'PaperMod'
paginate = 10
publishDir = "docs"

[params]
title= 'Ulimativos Github Page'
defaultTheme = "dark"
ShowReadingTime = true

[params.homeInfoParams]
Title = "Hi there wave"
Content = "Can be Info, links, about..."
