baseURL = 'https://ulimativo.github.io/'
languageCode = 'en-us'
title = 'Ulimativo@Gihub.io'
copyright = '2023 Ulimativo'
theme= 'PaperMod'
paginate = 10
publishDir = "docs"
enableEmoji = true
timeZone = "Europe/Vienna"

[params]
title= 'Ulimativos Github Page'
defaultTheme = "dark"
ShowReadingTime = true

[params.homeInfoParams]
Title = "Hi there! :wave:"
Content = "This is my Hugo-powered Github page."
